[project]
name = "Bon Vojojn Baza"
version = "0.2.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "QiMono", email = "albert.tan.2.pi.0@gmail.com" }
]
dependencies = [
  "flet==0.27.6",
  "flet_video"
]

[tool.flet]
include-package = ["flet_video"]
org = "vip.qimono.bonvojojnbaza"

# project display name that is used as an app title on Android and iOS home screens,
# shown in window titles and about app dialogs on desktop.
product = "Bon Vojojn Baza"

# company name to display in about app dialogs
company = "Qimono"

# copyright text to display in about app dialogs
copyright = "CopyLeft (c) 2025 by QiMono"

[tool.flet.app]
path = "src"

[tool.uv]
dev-dependencies = [
    "flet[all]==0.27.6",
]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
flet = {extras = ["all"], version = "0.27.6"}